### ISSUE TITLE
Invalid local database config setting causes crash

### ISSUE THREAD

**Issue by msporny** [digitalbazaar/bedrock-mongodb#11]
Is the value being checked here:

https://github.com/digitalbazaar/bedrock-mongodb/blob/master/lib/database.js#L763

supposed to be this, instead?

```javascript
if(!config.mongodb.local.enable) {
```

Hitting the above line in the Aseta code base causes the bedrock-mongodb module to crash.  There doesn't seem to be a default for it.

**Comment by dlongley** [comment]
Yes, I believe that's what it's supposed to be instead. This is @davidlehn's change so I'll ping him on it.

**Comment by dlongley** [comment]
Seems like maybe this line:

https://github.com/digitalbazaar/bedrock-mongodb/blob/master/lib/database.js#L743

Was supposed to be:

```js
var config = bedrock.config.mongodb;
```

Like others in the file. That would also mean some other adjustments.

**Comment by dlongley** [comment]
Closing via #12.
