### ISSUE TITLE
Update to 3.x driver

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-mongodb#19]
MongoDB 4.x requires the nodejs v3.x driver: https://docs.mongodb.com/manual/release-notes/4.0/#drivers

The 3.x driver is also required to access some of the latest mongodb 3.x additions.

Here's the list of breaking changes in the 3.x driver: https://github.com/mongodb/node-mongodb-native/blob/3.0/CHANGES_3.0.0.md

One of the big ones is that the `find` API has moved the `projection` parameter into `options.projection`.

Our code base will also be impacted by the changes in the bulkWrite APIs.  I would categorize these changes as improvements because the error handling in the 2.x bulkWrite APIs is really wonky which required silly tactics like this: https://github.com/digitalbazaar/bedrock-ledger-storage-mongodb/blob/master/lib/LedgerEventStorage.js#L134

**Comment by dmitrizagidulin** [comment]
Addressed by PR #33, closing.
