### ISSUE TITLE
Support `url` option in config

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-mongodb#2]
We should support providing a `url` option in the config for connecting to the database as an alternative (and `url` is given precedence) over `name`, etc. When this option is present, we will call `.connect` instead of creating a `Server` object and calling `.open`. We need to support separate `url` options for both remote and local databases so we don't mix connection options, etc. between the two. We also need to ensure the logging is updated to use `url` if provided.

**Comment by dlongley** [comment]
@mattcollier, feel free to reassign to someone else as desired/needed.

**Comment by mattcollier** [comment]
Landed https://github.com/digitalbazaar/bedrock-mongodb/commit/9fc33ed9535296c1ac2f4638bef95e7055f16485
