### ISSUE TITLE
Return buffer from `database.hash`

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-mongodb#23]
@dlongley what's the idea behind this fixme? 

https://github.com/digitalbazaar/bedrock-mongodb/blame/master/lib/index.js#L266

https://github.com/digitalbazaar/bedrock-mongodb/blob/master/lib/index.js#L266

What use case did you have in mind?

P.S. Anyone know the secret to get github to display code inline based on links?  From what I can tell, it just does it when it feels like it.

**Comment by dlongley** [comment]
You can remove the FIXME.
