### ISSUE TITLE
Uncaught MongoError, bedrock-mongodb@6, mongo client 2.x

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-mongodb#28]
```
     Uncaught MongoError: connection 5 to localhost:27017 closed
      at Function.MongoError.create (node_modules/mongodb-core/lib/error.js:29:11)
      at Socket.<anonymous> (node_modules/mongodb-core/lib/connection/connection.js:214:22)
      at TCP._handle.close (net.js:597:12)
```
This sort of error pops up on rare occasion on when looping on TestCloud.  It would be good to investigate this error and see if we can fail/recover more gracefully.

**Comment by aljones15** [comment]
do we know if `connection 5` means the fifth connection attempt or 1 of 5 concurrent connections? Perhaps localhost only allows a set number of concurrent connections?

**Comment by dlongley** [comment]
I'm closing as won't fix -- as a part of a very old version. We shouldn't put any effort toward this unless it comes up again with the new version.
