### ISSUE TITLE
Remove idGenerator in upcoming breaking release?

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-mongodb#34]
https://github.com/digitalbazaar/bedrock-mongodb/blob/master/lib/idGenerator.js

I believe this is legacy code that is no longer used for anything.  Can we destroy it?

**Comment by dlongley** [comment]
Let's drop it if we can. Should be dropped in/after PR #33 and before the next major release.

**Comment by aljones15** [comment]
This should not be that hard to do the id generator is only used in 4 places in the db repo:

https://github.com/search?q=org%3Adigitalbazaar+in%3Afile+DistributedIdGenerator+user%3Adigitalbazaar&type=Code

**Comment by dlongley** [comment]
I didn't see any active repos, only deprecated ones.

**Comment by dlongley** [comment]
This is related to the use of the `local` database in mongo. I don't think we use that anywhere anymore and, ideally, we'd remove support for it as well (who knows if the existing support functions properly). @mattcollier do you agree?

**Comment by mattcollier** [comment]
+1 to removing all the things.  We have not actually used `localCollection` for anything in years afaik.  I hope @davidlehn will respond here as well.

**Comment by davidlehn** [comment]
I think the need for this has been lost in the winds of time.  Could always bring it back if needed.

**Comment by aljones15** [comment]
idGenerator was removed and did not break tests in any dependent packages.
