### ISSUE TITLE
Replace use of `runOnceAsync` with `runOnce` before next release.

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-mongodb#36]
> Need to replace use of `runOnceAsync` with `runOnce`.
> 
> Thanks to new node 14 feature `--trace-warnings` figured out where this one was coming from!
> 
> ```
> (node:26039) DeprecationWarning: runOnceAsync() is deprecated. Use runOnce() instead.
>     at deprecatedCallbackified (util.js:210:5)
>     at initDatabase (/home/matt/bedrock-dev/bedrock-rsvp/test/node_modules/bedrock-mongodb/lib/index.js:146:64)
>     at runTask (/home/matt/bedrock-dev/bedrock-rsvp/test/node_modules/bedrock-mongodb/node_modules/async/dist/async.js:1634:13)
>     at /home/matt/bedrock-dev/bedrock-rsvp/test/node_modules/bedrock-mongodb/node_modules/async/dist/async.js:1572:13
>     at processQueue (/home/matt/bedrock-dev/bedrock-rsvp/test/node_modules/bedrock-mongodb/node_modules/async/dist/async.js:1582:13)
>     at Object.auto (/home/matt/bedrock-dev/bedrock-rsvp/test/node_modules/bedrock-mongodb/node_modules/async/dist/async.js:1568:5)
>     at init (/home/matt/bedrock-dev/bedrock-rsvp/test/node_modules/bedrock-mongodb/lib/index.js:145:9)
>     at internal/util.js:297:30
>     at new Promise (<anonymous>)
>     at init (internal/util.js:296:12)
> ```

Addressed the runOnceAsync issue here: https://github.com/digitalbazaar/bedrock-mongodb/pull/33/commits/24bb26da128b8be62f3178bf9f322e29bb4b0823

the code in that commit does not address removing `db.authenticate` yet.

_Originally posted by @aljones15 in https://github.com/digitalbazaar/bedrock-mongodb/pull/33#issuecomment-637078513_

**Comment by aljones15** [comment]
This has been merged into master so closing this as changes were made in that PR.
