### ISSUE TITLE
TODO/FIXME Count 2

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-mongodb#43]
- [x] TODO: merge similar callbacks below into single function
       Commit: (083eefe) Consolidate common code.
       File:  [lib/database.js:534](https://github.com/digitalbazaar/bedrock-mongodb/blob/master/lib/database.js#L534)
       Dave Longley commented 5 years ago

  - [ ] TODO: refactor to avoid removing user; driver doesn't seem to provide
       Commit: (6422e5e) Add mongodb 2.6+ support.
       File:  [lib/database.js:798](https://github.com/digitalbazaar/bedrock-mongodb/blob/master/lib/database.js#L798)
       Dave Longley commented 5 years ago

**Comment by dlongley** [comment]
All that remains is dealing with the user update/replacement. Maybe we just want to keep things as they are as well as it is simple.

**Comment by JSAssassin** [comment]
Closing. Opened new issue for the remaining TODO item.
