### ISSUE TITLE
Remove serverVersion checks

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-mongodb#46]
Previous this library supported versions of mongodb before the use of roles was implemented. We can now simplify the code by removing serverVersion checks such as this one:

https://github.com/digitalbazaar/bedrock-mongodb/blob/211284e1245d9c07e5cedb87ef2c5276da9a2c54/lib/index.js#L847-L852

p.s. do not go ahead with this unless there is consensus this is the right thing to do.

**Comment by dlongley** [comment]
We are keeping these checks in case of an accidental connection to an old mongodb server.
