### ISSUE TITLE
Update from async package async/await.

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-mongodb#47]
This is a major breaking change, but this library is core to functionality and lags behind other libraries significantly. We have previously made changes to bedrock events to make then use `async` and `await`, but this library still uses an older callback based library.

Here some notes on the work needed (**NOTE: these notes were based off of version `6.0.0`**):

## `lib/index.js`

- [ ] [switch init to async](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L90)
- [ ] [await initDatabase in init](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L134-L142)
- [ ] [await openLocal](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L143-L153)
- [ ] [await dropCollections](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L154-L160)
- [ ] [await openCollections](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L161-L162)
- [ ] [await createIndex](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L163-L168)
- [ ] [await setupLocal](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L169-L176)
- [ ] [openCollections change to async and dependent libs will need to remove the callback](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L196)
- [ ] [openCollection remove async.each in favor of a for loop on unopened await createCollection](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L205-L218)
- [ ] [mongo driver 3.5 createCollection docs (returns a promise if no callback is passed](http://mongodb.github.io/node-mongodb-native/3.5/api/Db.html#createCollection)
- [ ] [change openCollections to an async await pattern](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L219-L231)
- [ ] [mongo 3.5 collection api doc](http://mongodb.github.io/node-mongodb-native/3.5/api/Db.html#collection)
- [ ] [change createIndex to async await](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L338-L349)
- [ ] [mongo 3.5 createIndex (promise is no cb)](http://mongodb.github.io/node-mongodb-native/3.5/api/Collection.html#createIndex)
- [ ] [change getDistributedIdGen to async await](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L373-L392)
- [ ] ['_setupLocalDatabase' to async await](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L465-L509)
- [ ] ['_initDatabase' to async await](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L549-L637)
- [ ] ['_openDatabase' to async await](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L639-L708)
- [ ] ['_connect' to async await](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L710-L732)
- [ ] ['_createUser' to async await](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L734-L791)
- [ ] ['_getAdminCredentials' to async await](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L793-L813)
- [ ] ['_addLocalUser' to asyc await](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L833-L878)
- [ ] ['_dropCollections' to asyc await](https://github.com/digitalbazaar/bedrock-mongodb/blob/83750f29103b8d77667ffc3fcebd1b13a893513d/lib/index.js#L880-L908)

We will also need to  (finally) remove promisfy code from database setup steps in favor of simple await statements.

**Comment by davidlehn** [comment]
With recent updates this should be possible to convert now.  Two main choices:

1. Update internals and API to be pure async/await.  We likely already wrap the API in all other dependents with promisify, so updates would likely not be too difficult.  I imagine any other users probably do the same.  However, everything would have to be updated at once which may be painful.
2. Update the internals to async/await, but wrap with callbackify for now.  It's not as nice as the pure approach, but would simplify updating the many dependent packages over time.  The callback API could be marked as deprecated and removed in the next major release.

I lean towards the pure async/await API.  With a major version bump npm should notify about packages that need updating.  And the code will fail if not updated.  It may be a bit painful to handle many packages, but the updates are likely not difficult.  If time is an issue, the callbackify approach would help.

**Comment by dlongley** [comment]
Everything here is done except a major breaking release that fully removes a few remaining functions that still support (but also use promises) callbacks. Closing. I'll open another issue to finally remove the other `brCallbackify` stuff in the next major release.
