### ISSUE TITLE
mongodb-uri is out of date

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-mongodb#48]
This package: https://www.npmjs.com/package/mongodb-uri

has not been updated in 6 years.

Meaning this code:

https://github.com/digitalbazaar/bedrock-mongodb/blob/211284e1245d9c07e5cedb87ef2c5276da9a2c54/lib/index.js#L97-L129

is also out of date.

We should probably just allow users to connect using the url specified and not try to get settings out of the url.

**Comment by dlongley** [comment]
This package is no longer used, closing.
