### ISSUE TITLE
Database init

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-mongodb#5]
In troubleshooting this issue: https://github.com/digitalbazaar/bedrock-mongodb/pull/4

I found that when attempting to start bedrock-idp in test mode that the following code block was running 7 times.

https://github.com/digitalbazaar/bedrock-mongodb/blob/master/lib/database.js#L129-L186

In the case of test mode where the dropCollection.onInit option is set, the collections are being created and dropped 7 times on startup.

**Comment by mattcollier** [comment]
The number of iterations appears to be related to the number of bedrock.config.core.workers configured.

**Comment by dlongley** [comment]
Using the drop collections feature is not supported w/multiple workers. It only runs in test mode which is intentionally a single worker simple process everywhere in our tests. I'm going to close this. If we want to enable using this on multiple workers in the future, it needs to be moved inside a `bedrock.runOnce` block.
