### ISSUE TITLE
Mongo ensureIndex() is deprecated

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-mongodb#6]
https://docs.mongodb.com/manual/reference/method/db.collection.ensureIndex/

Deprecated since version 3.0.0: db.collection.ensureIndex() is now an alias for db.collection.createIndex().

Using this here:
- https://github.com/digitalbazaar/bedrock-mongodb/blob/master/lib/database.js#L348
- https://github.com/digitalbazaar/bedrock-mongodb/blob/master/lib/database.js#L495

**Comment by dlongley** [comment]
It's really up to what the driver does to figure out what we should do here.

**Comment by dlongley** [comment]
Docs suggest that we use `createIndexes` instead:

http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#ensureIndex
