### ISSUE TITLE
Remove usage of `brCallbackify` and callback support in next major release

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-mongodb#72]
Everything here is done except a major breaking release that fully removes a few remaining functions that still support (but also use promises) callbacks. Closing. I'll open another issue to finally remove the other `brCallbackify` stuff in the next major release.

_Originally posted by @dlongley in https://github.com/digitalbazaar/bedrock-mongodb/issues/47#issuecomment-880096005_

**Comment by davidlehn** [comment]
Remember to update README examples when this is worked on.

**Comment by dlongley** [comment]
Fixed in version 8, closing.
