### ISSUE TITLE
Add tests for Authentication

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-mongodb#75]
We have no tests for authentication and it's causing problems.

There is an existing issue suggesting using a docker container for production settings:

https://github.com/digitalbazaar/bedrock-mongodb/issues/39

The major challenges to testing auth is that existing tests test against mongodb setups on developer's computers. There are existing temp mongodb frameworks that might be able to solve this. Another option would be to start a docker mongodb container on a port different from the usual development port and give it an pre-set `mongod.conf` file with auth turned on. Then test against that container with the auth tests.

Auth tests also need to include adding a new user which does pause the CLI while you enter the admin details.
There might be more tests we need that involve auth.

**Comment by dlongley** [comment]
Addressed by #85.
