### ISSUE TITLE
TODO: Refactor to avoid removing user

### ISSUE THREAD

**Issue by JSAssassin** [digitalbazaar/bedrock-mongodb#77]
TODO: refactor to avoid removing user; driver doesn't seem to provide
Commit: (6422e5e) Add mongodb 2.6+ support.
File: lib/database.js:798
Dave Longley commented 5 years ago

Comments:
https://github.com/digitalbazaar/bedrock-mongodb/issues/43#issuecomment-880097436

**Comment by dlongley** [comment]
This has been resolved, closing.
