### ISSUE TITLE
Consider removal of `prompt` dependency and the functionality it provides

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-mongodb#82]
https://github.com/digitalbazaar/bedrock-mongodb/blob/4fb346d7913a708856c7b711c2e7c590ed168571/lib/cli.js#L58-L84

There is a security vulnerability in the `async` child dependency of the `prompt` module required here.

The functionality provided by the `prompt` module that allows users to enter admin credentials at the command line at startup is obsolete for modern containerized applications.

I propose that this functionality be removed entirely along with the related dependencies.

Related: https://github.com/digitalbazaar/bedrock-mongodb/issues/79

**Comment by dlongley** [comment]
I think we could safely remove it without doing a major release -- thoughts?

**Comment by mattcollier** [comment]
I believe this is definitely a breaking change as it removes functionality.  I don't believe that the fact that the functionality is not used (by Digital Bazaar) is relevant to the decision.

**Comment by dlongley** [comment]
Removed in version 10.
